fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

default:
    resource: "@BaseBundle/Controller/"
    type:      annotation
    prefix:   /

component:
    resource: "@BaseBundle/Controller/"
    type:      annotation
    prefix:   /